# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd12ac5d8260522c2541b4e26554804c00fbdcd01a406f973ed5b8e0f22025c4a440124887d0249a6d895d8c3a97fb75a5186b89863a5a232ce1df5ebac543ae

test:
  secret_key_base: 5fc98d9de2257b842ea7625110d586a86e3572e06391b32dfabdc2b9db598ab68f69ee29e3ca5f1022f6771ff7e817405f1fc14cd90558438fd9b221bebda8ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
